# Generated by Django 6.1.1 on 2026-09-05 13:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short buyer-facing category name, such as Electronics.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe category value, such as electronics.', max_length=110, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Clear product title shown on cards and order lines.', max_length=200)),
                ('description', models.TextField(help_text='Detailed buyer-facing description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current unit price in Indian rupees.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of units currently available for purchase.')),
                ('image', models.ImageField(blank=True, help_text='Optional product photo; JPG, PNG, or WEBP is recommended.', null=True, upload_to='products/%Y/%m/%d/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active products are visible and purchasable by buyers.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp recorded when the seller first created the product.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp refreshed whenever the product is edited.')),
                ('category', models.ForeignKey(help_text='Catalog category used for buyer browsing and filtering.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('seller', models.ForeignKey(help_text='Seller account that owns and manages this product.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_active', 'category'], name='product_active_cat')],
            },
        ),
    ]
